#服务和tomcat设置
server:
  port: 8080
  servlet:
    context-path: /uac
  tomcat:
    uri-encoding: UTF-8
    basedir: /usr/local/tomcat
    max-threads: 2000
  compression:
    enabled: true
    mime-types:
    - application/javascript,text/html,text/xml,text/javascript,text/css,text/plain,application/json,application/x-javascript,image/gif,image/jpeg,image/png,text/html,application/xhtml+xml,application/xml

info:
  status: ok
  
#spring配置
spring:
  http:
    encoding:
      force: true
      force-request: true
      force-response: true

#日志
# logging:
#  config: classpath:logback-spring.xml

#加密
jasypt:
  encryptor:
    password: 123456
