#服务和tomcat设置
server:
  port: 8080
  servlet:
    context-path: /uac
  tomcat:
    uri-encoding: UTF-8
#    basedir: /usr/local/tomcat
    max-threads: 2000
  compression:
    enabled: true
    mime-types:
    - application/javascript,text/html,text/xml,text/javascript,text/css,text/plain,application/json,application/x-javascript,image/gif,image/jpeg,image/png,text/html,application/xhtml+xml,application/xml

info:
  status: ok

# redis相关配置
spring:
  redis:
    database: 0
    password: 123456 #密码
    port: 6379
    timeout: 0
    host: localhost
    pool:
      max-active: 8 #最大连接数
      max-idle: 8 #最大空闲连接数
      max-wait: -1 #最大等待时间
      min-idle: 0
#    sentinel:
#      master: master1
#      nodes: 172.16.33.216:16001,172.16.33.216:16002

server:
  port: 9090



#日志
# logging:
#  config: classpath:logback-spring.xml

#加密
jasypt:
  encryptor:
    password: 123456

