#服务和tomcat设置
server:
  port: 8080
  servlet:
    context-path: /uac
  tomcat:
    uri-encoding: UTF-8
    basedir: /usr/local/tomcat
    max-threads: 2000
  compression:
    enabled: true
    mime-types:
    - application/javascript,text/html,text/xml,text/javascript,text/css,text/plain,application/json,application/x-javascript,image/gif,image/jpeg,image/png,text/html,application/xhtml+xml,application/xml

info:
  status: ok
  
#spring配置
spring:
  http:
    encoding:
      force: true
      force-request: true
      force-response: true
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-name: list
      #集群节点地址列表，用逗号分隔。如果没有指定，就启动一个客户端节点
      cluster-nodes: 192.168.1.182:9300,192.168.1.183:9300,192.168.1.184:9300

elasticsearch:
  clusterName: list
  firstIp: 192.168.1.182
  firstPort: 9300
  secondIp: 192.168.1.183
  secondPort: 9300
  thirdIp: 192.168.1.184
  thirdPort: 9300


#日志
# logging:
#  config: classpath:logback-spring.xml

#加密
jasypt:
  encryptor:
    password: 123456

